### ISSUE TITLE
Unable to mount multiple files from the same directory

### ISSUE THREAD

**Issue by radu-matei** [cnabio/duffle#224]
Trying to use multiple files from the same directory as credentials for an installation fails. For example, the following credentials file:

```yaml
name: aks
credentials:
  - name: azure_sub
    source:
      env: AZURE_SUB
    destination:
      env: SUBSCRIPTION

  - name: az-token
    source:
      path: $HOME/.azure/accessTokens.json
    destination:
      path: /root/.azure/accessTokens.json

  - name: az-profile
    source:
      path: $HOME/.azure/azureProfile.json
    destination:
      path: /root/.azure/azureProfile.json

```

Trying to execute:

```
docker: Error response from daemon: Duplicate mount point: /root/.azure.
```

Here's what volumes Duffle tries to mount:

```
--volume /tmp/duffle-volume-611069134:/root/.azure --volume /tmp/duffle-volume-414169557:/root/.azure
```

Duffle will copy the two files into two new directories, but will mount them inside the same directory in the container - which is where the error is coming from.
